# Site settings
name: Xu Ma
email: maxuMelody@foxmail.com
author: Xu Ma
url: https://13952522076.github.io
resume_site: http://blog.csdn.net/maxu12345
github: https://github.com/13952522076/
baseurl: ""
description: My personal blog
meta_description:  Xu Ma: 醉后不知天在水，满船清梦压星河。
motto: 醉后不知天在水，满船清梦压星河。
banner: 醉后不知天在水，满船清梦压星河。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 13952522076

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

